### ISSUE TITLE
Repeated Article Text

### ISSUE THREAD

**Issue by ufxela** [TheStanfordDaily/archives-text#15]
Body of text is repeated in most articles ~8 times.

ex:
https://github.com/TheStanfordDaily/archives-text/blob/master/2014/06/13/MODSMD_ARTICLE9.article.txt

**Comment by epicfaace** [comment]
wow, didn't realize it was that bad (8 times)

**Comment by ufxela** [comment]
fixed in https://github.com/TheStanfordDaily/archives-text/commit/e84a071c45948e495bcf5987ca15be0c0df54813
