### ISSUE TITLE
Subtitle is on two lines

### ISSUE THREAD

**Issue by epicfaace** [TheStanfordDaily/archives-text#2]
https://github.com/TheStanfordDaily/archives-text/blob/master/1903/05/13/MODSMD_ARTICLE1.article.txt

![image](https://user-images.githubusercontent.com/1689183/57826826-c1e02e00-7759-11e9-95dc-aa52d52314ac.png)

**Comment by hesyifei** [comment]
maybe we can remove any new line in subtitles? We should check the original METS file for this to be sure.

**Comment by epicfaace** [comment]
Same with titles: https://github.com/TheStanfordDaily/archives-text/blob/master/1902/05/22/MODSMD_ARTICLE9.article.txt
